version: "3.9"

services:
  web:
    build: "./docker/php"
    container_name: ${APP_NAME}_php
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./docker/vhosts/default.conf:/etc/apache2/sites-enabled/default.conf"
      - "./docker/log/apache2:/var/log/apache2"
      - "./app:/var/www/html"
    depends_on:
      - mysqldb
  mysqldb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${APP_NAME}_${MARIADB_HOST}
    restart: always
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/data/db/mysql:/var/lib/mysql"
      - "./docker/mysql/conf.d/my.conf:/etc/mysql/conf.d/my.cnf"
      - "./app:/var/www/html"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PMA_VERSION}
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MARIADB_HOST}
    restart: always
    depends_on:
      - web
      - mysqldb